version: '3'
services:
...
  apache2:
    build: .
    hostname: m1-4.ephec-ti.be
    restart: always
    volumes:
      - etcletsencrypt:/etc/letsencrypt
      - varletsencrypt:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    environment:
      LETS_ENCRYPT_EMAIL: "he201881@students.ephec.be"
      LETS_ENCRYPT_DOMAINS: "m1-4.ephec-ti.be,www.m1-4.ephec-ti.be,b2b.m1-4.ephec-ti.be"
...
volumes:
  varletsencrypt:
  etcletsencrypt: